[package]
name = "pbooks"
version = "0.1.0"
authors = ["Edward Yang <edward.yang6771@gmail.com>"]

[dependencies]
hyper = "0.6"
time = "0.1.34"
term-painter = { git = "https://github.com/honorabrutroll/term-painter" }
terminal_size = "0.1.1"
